export const ADMIN_SIGN_IN_SUCCESS = "ADMIN_SIGN_IN_SUCCESS";

export const ADMIN_SIGN_IN_FAIL = "ADMIN_SIGN_IN_FAIL";

export const ADMIN_GET_ACCOUNT_SUCCESS = "ADMIN_GET_ACCOUNT_SUCCESS";

export const ADMIN_LOG_OUT = "ADMIN_LOG_OUT";

export const FETCH_ADMIN_SUCCESS = "FETCH_ADMIN_SUCCESS";

export const FETCH_ADMIN_FAIL = "FETCH_ADMIN_FAIL";

export const ADMIN_REFRESH_TOKEN_SUCCESS = "ADMIN_REFRESH_TOKEN_SUCCESS";

export const SET_ADMIN_ACCESSTOKEN = "SET_ADMIN_ACCESSTOKEN";

export const SET_ADMIN_REFRESHTOKEN = "SET_ADMIN_REFRESHTOKEN";