export const ADMIN_SIGN_IN_SUCCESS = "ADMIN_SIGN_IN_SUCCESS";

export const ADMIN_SIGN_IN_FAIL = "ADMIN_SIGN_IN_FAIL";

export const ADMIN_LOG_OUT = "ADMIN_LOG_OUT";

export const FETCH_ADMIN_SUCCESS = "FETCH_ADMIN_SUCCESS";

export const FETCH_ADMIN_FAIL = "FETCH_ADMIN_FAIL";